#!/usr/bin/env bash


#Check for a bucket name
if [ -z "$1" ]; then
  echo "No bucket name is given"
  exit 1
fi

BUCKET_NAME=$1
echo "Enter region: " 
read region;

if [ -z "$region" ]; then
    echo "Enter a region name"
    fi

if [ "$region" = "us-east-1" ]; then
    aws s3api create-bucket --bucket $BUCKET_NAME --region $region --query Location --output text
else
#LocationConstraint is required for region out of us-east-1
    aws s3api create-bucket --bucket $BUCKET_NAME --region $region --query Location --output text --create-bucket-configuration LocationConstraint=$region
fi
