#!/usr/bin/env bash


#Check for a bucket name
if [ -z "$1" ]; then
  echo "No bucket name is given"
  exit 1
fi

BUCKET_NAME=$1
echo "Enter region: " 
read region;

if [ -z "$region" ]; then
    echo "Enter a region name"
    fi

if [ "$region" = "us-east-1" ]; then
    aws s3api create-bucket --bucket $BUCKET_NAME --region $region
else
    aws s3api create-bucket --bucket $BUCKET_NAME --region $region --create-bucket-configuration LocationConstraint=$region
fi
