#!/usr/bin/env bash

set -e
echo "Newest bucket"
# uses JQ to filter the output according to the need
#[0] to get the first bucket 
aws s3api list-buckets | jq '.Buckets | sort_by(.CreationDate) | reverse | .[0] | .Name'